# 제품 모드
[build]
  command = "npm run build"
  functions = "functions" # netlify 서버리스 함수가 작성된 디렉토리
  publish = "build" # 프로젝트 build 번들 디렉토리 지정

# 개발 모드
[dev]
  framework = "#custom" # 감지할 프로젝트 유형
  command = "npm run start" # 개발 서버 실행 script
  targetPort = "3000" # 연결할 프로젝트 개발 서버 포트
  port = 8888 # 출력할 netlify server 포트
  publish = "build" # 프로젝트의 정적 콘텐츠 디렉토리
  autoLaunch = true # netlify 서버가 준비되면 자동으로 브라우저 오픈 여부